#!/usr/bin/env bash
# Installs every agent and skill in this repo into Claude Code (~/.claude),
# OpenCode (~/.config/opencode), and Codex (~/.codex). Idempotent:
# re-running replaces symlinks/generated Codex agents; existing real files
# are backed up to
# <path>.bak-<timestamp>-<pid> before being replaced. Dangling symlinks
# pointing back into this repo are cleaned up at the start of each run
# so removed items disappear.
#
# Repo layout:
#   agents/<name>/*.md           - subagents (one or more .md files per folder)
#   agents/<name>/commands/*.md  - slash commands scoped to that agent
#   skills/<name>/SKILL.md       - skill body (required)
#   skills/<name>/...            - any sibling files (templates, scripts, refs)
#                                  are included because the skill folder is
#                                  symlinked as a whole
#   skills/<name>/commands/*.md  - slash commands scoped to that skill
#
# Install targets:
#   Subagents:     ~/.claude/agents/<name>.md
#                  ~/.config/opencode/agents/<name>.md
#                  ~/.codex/agents/<name>.toml      (generated from .md)
#   Skills:        ~/.claude/skills/<name>            (folder symlink)
#                  ~/.config/opencode/skills/<name>   (folder symlink)
#                  ~/.codex/skills/<name>             (folder symlink)
#   Commands:      ~/.claude/commands/<name>.md
#                  ~/.config/opencode/commands/<name>.md
#                  (Codex commands are not installed; use skills instead)
#   AGENTS.md:     ~/.claude/AGENTS.md
#                  ~/.config/opencode/AGENTS.md
#                  ~/.codex/AGENTS.md

set -euo pipefail
shopt -s nullglob

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${HOME}/.claude"
OPENCODE_DIR="${HOME}/.config/opencode"
CODEX_DIR="${CODEX_HOME:-${HOME}/.codex}"
GENERATED_MARKER="# Generated by personal-skills install.sh from "

# Generate a backup path that doesn't already exist. Combines second-resolution
# timestamp with PID and a tilde-suffix fallback to avoid collisions when the
# script runs multiple times within the same second.
backup_path() {
  local dst="$1"
  local backup="${dst}.bak-$(date +%s)-$$"
  while [[ -e "$backup" ]]; do
    backup="${backup}~"
  done
  printf '%s\n' "$backup"
}

# Symlink a single file. Replaces an existing symlink; backs up a real file.
link_file() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  if [[ -L "$dst" ]]; then
    rm "$dst"
  elif [[ -e "$dst" ]]; then
    local backup
    backup="$(backup_path "$dst")"
    echo "  backup: $dst -> $backup"
    mv "$dst" "$backup"
  fi
  ln -s "$src" "$dst"
  echo "  link:   $dst"
}

# Symlink a whole directory. Replaces an existing symlink; backs up a real dir.
link_dir() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  if [[ -L "$dst" ]]; then
    rm "$dst"
  elif [[ -e "$dst" ]]; then
    local backup
    backup="$(backup_path "$dst")"
    echo "  backup: $dst -> $backup"
    mv "$dst" "$backup"
  fi
  ln -s "$src" "$dst"
  echo "  link:   $dst/"
}

# Extract a simple one-line YAML frontmatter scalar. This repo intentionally
# keeps agent frontmatter small, so a full YAML parser would be unnecessary.
frontmatter_scalar() {
  local key="$1" src="$2"
  awk -v key="$key" '
    $0 == "---" { section++; next }
    section == 1 && $0 ~ "^" key ":[[:space:]]*" {
      sub("^" key ":[[:space:]]*", "")
      print
      exit
    }
    section >= 2 { exit }
  ' "$src"
}

frontmatter_bool() {
  local key="$1" src="$2"
  awk -v key="$key" '
    $0 == "---" { section++; next }
    section == 1 && $0 ~ /^[^[:space:]]/ && $0 !~ /^tools:/ {
      in_tools = 0
    }
    section == 1 && $0 ~ /^tools:[[:space:]]*$/ {
      in_tools = 1
      next
    }
    section == 1 && in_tools && $0 ~ "^[[:space:]]+" key ":[[:space:]]*" {
      sub("^[[:space:]]+" key ":[[:space:]]*", "")
      print
      exit
    }
    section >= 2 { exit }
  ' "$src"
}

frontmatter_body() {
  awk '
    $0 == "---" { section++; next }
    section >= 2 { print }
  ' "$1"
}

toml_escape() {
  sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

toml_escape_multiline() {
  sed -e 's/\\/\\\\/g' -e 's/"""/\\"""/g'
}

# Codex custom agents are TOML files, unlike the Markdown agent files used by
# Claude Code and OpenCode. Generate them from the Markdown source of truth.
install_codex_agent() {
  local src="$1"
  local name description write_tool edit_tool bash_tool sandbox_mode dst tmp body

  name="$(frontmatter_scalar name "$src")"
  description="$(frontmatter_scalar description "$src")"
  write_tool="$(frontmatter_bool write "$src")"
  edit_tool="$(frontmatter_bool edit "$src")"
  bash_tool="$(frontmatter_bool bash "$src")"

  if [[ -z "$name" ]]; then
    name="$(basename "$src" .md)"
  fi
  if [[ -z "$description" ]]; then
    description="Custom agent generated from $(basename "$src")."
  fi

  sandbox_mode="read-only"
  if [[ "$write_tool" == "true" || "$edit_tool" == "true" || "$bash_tool" == "true" ]]; then
    sandbox_mode="workspace-write"
  fi

  dst="$CODEX_DIR/agents/${name}.toml"
  tmp="${dst}.tmp-$$"
  mkdir -p "$(dirname "$dst")"

  body="$(frontmatter_body "$src" | toml_escape_multiline)"
  {
    printf '%s%s\n' "$GENERATED_MARKER" "$src"
    printf 'name = "%s"\n' "$(printf '%s' "$name" | toml_escape)"
    printf 'description = "%s"\n' "$(printf '%s' "$description" | toml_escape)"
    printf 'sandbox_mode = "%s"\n' "$sandbox_mode"
    printf 'developer_instructions = """\n%s\n"""\n' "$body"
  } >"$tmp"

  if [[ -L "$dst" ]]; then
    rm "$dst"
  elif [[ -e "$dst" ]] && ! head -n 1 "$dst" | grep -Fq "$GENERATED_MARKER"; then
    local backup
    backup="$(backup_path "$dst")"
    echo "  backup: $dst -> $backup"
    mv "$dst" "$backup"
  fi

  mv "$tmp" "$dst"
  echo "  write:  $dst"
}

# Remove symlinks under $1 whose target points into $ROOT but no longer exists.
# Keeps the install idempotent even after items are renamed or deleted.
prune_dangling() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  while IFS= read -r -d '' link_path; do
    local target
    target="$(readlink "$link_path")"
    if [[ "$target" == "$ROOT"/* && ! -e "$link_path" ]]; then
      echo "  prune:  $link_path (target $target gone)"
      rm "$link_path"
    fi
  done < <(find "$dir" -type l -print0 2>/dev/null)
}

prune_generated_codex_agents() {
  local dir="$CODEX_DIR/agents"
  [[ -d "$dir" ]] || return 0

  for agent_file in "$dir"/*.toml; do
    [[ -e "$agent_file" ]] || continue

    local first_line src
    first_line="$(head -n 1 "$agent_file")"
    if [[ "$first_line" == "$GENERATED_MARKER"* ]]; then
      src="${first_line#"$GENERATED_MARKER"}"
      if [[ "$src" == "$ROOT"/* && ! -f "$src" ]]; then
        echo "  prune:  $agent_file (source $src gone)"
        rm "$agent_file"
      fi
    fi
  done
}

# Remove empty subdirectories one level deep inside $1. Used after pruning so
# orphaned skill folders (e.g. ~/.claude/skills/old-skill/) don't accumulate.
sweep_empty() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  find "$dir" -mindepth 1 -maxdepth 1 -type d -empty -delete 2>/dev/null || true
}

install_agent() {
  local agent_dir="$1"
  local agent_name
  # Strip any trailing slash that the glob "$ROOT/agents"/*/ leaves behind so
  # generated Codex source markers are stable.
  agent_dir="${agent_dir%/}"
  agent_name="$(basename "$agent_dir")"

  echo ""
  echo "== agent: $agent_name =="

  local found=0
  for f in "$agent_dir"/*.md; do
    found=1
    local name
    name="$(basename "$f")"
    link_file "$f" "$CLAUDE_DIR/agents/$name"
    link_file "$f" "$OPENCODE_DIR/agents/$name"
    install_codex_agent "$f"
  done
  if [[ $found -eq 0 ]]; then
    echo "  skip:   no .md files in $agent_dir"
  fi

  if [[ -d "$agent_dir/commands" ]]; then
    for f in "$agent_dir/commands"/*.md; do
      local name
      name="$(basename "$f")"
      link_file "$f" "$CLAUDE_DIR/commands/$name"
      link_file "$f" "$OPENCODE_DIR/commands/$name"
    done
  fi
}

install_skill() {
  local skill_dir="$1"
  local skill_name
  skill_name="$(basename "$skill_dir")"
  # Strip any trailing slash that the glob "$ROOT/skills"/*/ leaves behind so
  # `ln -s` doesn't dereference the source.
  skill_dir="${skill_dir%/}"

  echo ""
  echo "== skill: $skill_name =="

  if [[ ! -f "$skill_dir/SKILL.md" ]]; then
    echo "  skip:   no SKILL.md found"
    return 0
  fi

  # Symlink the whole skill folder so any sibling files (templates, scripts,
  # references) come along automatically.
  link_dir "$skill_dir" "$CLAUDE_DIR/skills/$skill_name"
  link_dir "$skill_dir" "$OPENCODE_DIR/skills/$skill_name"
  link_dir "$skill_dir" "$CODEX_DIR/skills/$skill_name"

  # Commands inside skills are installed to the platform-wide commands dirs,
  # not to the skill folder. They're already reachable via the folder symlink,
  # but OpenCode/Claude Code only discover commands from the dedicated paths.
  if [[ -d "$skill_dir/commands" ]]; then
    for f in "$skill_dir/commands"/*.md; do
      local name
      name="$(basename "$f")"
      link_file "$f" "$CLAUDE_DIR/commands/$name"
      link_file "$f" "$OPENCODE_DIR/commands/$name"
    done
  fi
}

echo "Installing from $ROOT"

echo ""
echo "Pruning dangling symlinks pointing into this repo..."
prune_dangling "$CLAUDE_DIR/agents"
prune_dangling "$CLAUDE_DIR/skills"
prune_dangling "$CLAUDE_DIR/commands"
prune_dangling "$CLAUDE_DIR/AGENTS.md"
prune_dangling "$OPENCODE_DIR/agents"
prune_dangling "$OPENCODE_DIR/skills"
prune_dangling "$OPENCODE_DIR/commands"
prune_dangling "$OPENCODE_DIR/AGENTS.md"
prune_dangling "$CODEX_DIR/skills"
prune_dangling "$CODEX_DIR/AGENTS.md"
prune_generated_codex_agents

# Sweep up any now-empty skill folders left behind by prior installs that
# symlinked SKILL.md rather than the whole folder.
sweep_empty "$CLAUDE_DIR/skills"
sweep_empty "$OPENCODE_DIR/skills"
sweep_empty "$CODEX_DIR/skills"

for d in "$ROOT/agents"/*/; do
  install_agent "$d"
done

for d in "$ROOT/skills"/*/; do
  install_skill "$d"
done

if [[ -f "$ROOT/AGENTS.md" ]]; then
  echo ""
  echo "== AGENTS.md =="
  link_file "$ROOT/AGENTS.md" "$CLAUDE_DIR/AGENTS.md"
  link_file "$ROOT/AGENTS.md" "$OPENCODE_DIR/AGENTS.md"
  link_file "$ROOT/AGENTS.md" "$CODEX_DIR/AGENTS.md"
fi

cat <<'EOF'

Done.

Notes:
  - Claude Code ignores OpenCode-specific frontmatter ('mode', 'temperature',
    'permission'). Permission enforcement only applies in OpenCode - in Claude
    Code, subagents inherit the parent session's permission mode.
  - Codex agents are generated as TOML under ~/.codex/agents. The Markdown
    agent files remain the source of truth for Claude Code and OpenCode.
  - To uninstall, remove the symlinks under:
      ~/.claude/{agents,skills,commands} and ~/.claude/AGENTS.md
      ~/.config/opencode/{agents,skills,commands} and ~/.config/opencode/AGENTS.md
      ~/.codex/{agents,skills} and ~/.codex/AGENTS.md
EOF
